/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MEASUREMENT_MODE_REQUEST PACKING
package calplug.bluetoothsri.com.MAVLink.common;
import calplug.bluetoothsri.com.MAVLink.MAVLinkPacket;
import calplug.bluetoothsri.com.MAVLink.Messages.MAVLinkMessage;
import calplug.bluetoothsri.com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Request for a given measurement mode. 1 -> eight, 2 -> eight w/ acc., 3 -> nine, 4 -> nine w/ acc.
*/
public class msg_measurement_mode_request extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST = 2;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST;


      
    /**
    * Mode of measurement
    */
    public short mode;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST;
              
        packet.payload.putUnsignedByte(mode);
        
        return packet;
    }

    /**
    * Decode a measurement_mode_request message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.mode = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_measurement_mode_request(){
        msgid = MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_measurement_mode_request(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST;
        unpack(mavLinkPacket.payload);        
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MEASUREMENT_MODE_REQUEST -"+" mode:"+mode+"";
    }
}
        