/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TILE_MEASUREMENTS_EIGHT PACKING
package calplug.bluetoothsri.com.MAVLink.common;
import calplug.bluetoothsri.com.MAVLink.MAVLinkPacket;
import calplug.bluetoothsri.com.MAVLink.Messages.MAVLinkMessage;
import calplug.bluetoothsri.com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Measurements from 
*/
public class msg_tile_measurements_eight extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT = 100;
    public static final int MAVLINK_MSG_LENGTH = 97;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT;


      
    /**
    * Data from magnetometers
    */
    public float mag_data[] = new float[24];
      
    /**
    * Tile this data is from
    */
    public short tile_number;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT;
              
        
        for (int i = 0; i < mag_data.length; i++) {
            packet.payload.putFloat(mag_data[i]);
        }
                    
              
        packet.payload.putUnsignedByte(tile_number);
        
        return packet;
    }

    /**
    * Decode a tile_measurements_eight message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
         
        for (int i = 0; i < this.mag_data.length; i++) {
            this.mag_data[i] = payload.getFloat();
        }
                
              
        this.tile_number = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_tile_measurements_eight(){
        msgid = MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_tile_measurements_eight(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_TILE_MEASUREMENTS_EIGHT -"+" mag_data:"+mag_data+" tile_number:"+tile_number+"";
    }
}
        